"""Add SmartDecks and remove Card deck_id

Revision ID: 87ca8ff78684
Revises: 4e770de6e52f
Create Date: 2026-06-08 19:04:02.827050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ca8ff78684'
down_revision: Union[str, Sequence[str], None] = '4e770de6e52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filter_criteria', sa.JSON().with_variant(postgresql.JSONB, "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_smart_decks_filter_criteria_gin', 'smart_decks', ['filter_criteria'], unique=False, postgresql_using='gin')

    # We must explicitly name the Postgres constraint
    op.drop_constraint('cards_deck_id_fkey', 'cards', type_='foreignkey')
    op.drop_column('cards', 'deck_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deck_id', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'cards', 'decks', ['deck_id'], ['id'])
    op.drop_index('ix_smart_decks_filter_criteria_gin', table_name='smart_decks', postgresql_using='gin')
    op.drop_table('smart_decks')
    # ### end Alembic commands ###
